apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

nodeGroups:
  - name: demo-monitoring
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyName: ec2key
